import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/widgets/header";
import Footer from "@/widgets/footer";

import "../styles";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${roboto.variable} antialiased`}
			>
				<div className="container mx-auto min-h-screen flex flex-col">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
